### PR TITLE
Feat/ts types build

### PR DESCRIPTION
**Pull request by wdavidw**
@LucasDemea Could you have a look at this branch, it uses rollup to generate compressed/merged js and d.ts files with rollup.

### CODE REVIEW

**Comment by LucasDemea** [comment]
There are some unnecessary steps. You don't need a specific tsconfig for types. Instead you can use the [declarationDir](https://www.typescriptlang.org/tsconfig/#declarationDir) property.
I can handle the bundle config if you want, as I already did it in previous commits.
If you need a GH action workflow to build and deploy to npm, I can handle this too.

**Comment by LucasDemea** [comment]
I'd also suggest to use a release tool such as [release-please](https://github.com/googleapis/release-please) or [semantic-release](https://github.com/semantic-release/semantic-release) to automate the semver based on semantic commits.

**Comment by LucasDemea** [comment]
Is there a reason for not keeping the .lock file versioned ?

**Comment by wdavidw** [comment]
> There are some unnecessary steps. You don't need a specific tsconfig for types. Instead you can use the [declarationDir](https://www.typescriptlang.org/tsconfig/#declarationDir) property.

I faced a lot of problems when using `declarationDir` inside rollup (the property is commented at the moment). The path resolution seems very buggy. Also, I wanted a single merged type file which is why I am using `rollup-plugin-dts`. Maybe I am wrong.

> If you need a GH action workflow to build and deploy to npm, I can handle this too.

Not in this PR, I also have workflows at disposal but feel free to propose later on.

> I'd also suggest to use a release tool such as [release-please](https://github.com/googleapis/release-please) or [semantic-release](https://github.com/semantic-release/semantic-release) to automate the semver based on semantic commits.

Semantic versioning is integrated with `standard-version`, eg `npm run release:patch`

> Is there a reason for not keeping the .lock file versioned ?

Yes, I consider lock files required for end application to ensure reproductive deployments but not desirable for libraries.

**Comment by LucasDemea** [comment]
Indeed I think dts plugin is required to merge types, but I think we can still manage a config not involving a specific tsconfig for types. I'll check this when I'll get some time.

**Comment by wdavidw** [comment]
I such case, I propose to merge that branch and create a new PR if a better and simpler approach is found.

**Pull request closed without merging**
